version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_DATABASE=prestashop_db
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '3306:3306'

  prestashop:
    image: 'bitnami/prestashop:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - ALLOW_EMPTY_PASSWORD=no
      - PRESTASHOP_DATABASE_USER=${DATABASE_USER}
      - PRESTASHOP_DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - PRESTASHOP_DATABASE_NAME=prestashop_db
      - PRESTASHOP_HOST=${PUBLIC_IP}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
